Use portable bash shebang everywhere (#208)

diff --git a/dev-scripts/git-hooks/pre-commit b/dev-scripts/git-hooks/pre-commit
--- a/dev-scripts/git-hooks/pre-commit
+++ b/dev-scripts/git-hooks/pre-commit
@@ -1,3 +1,12 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+# Exit on first failure.
+set -e
+
+# Exit on unset variable.
+set -u
+
+# Echo commands before executing them, by default to stderr.
+set -x
 
 ./dev-scripts/build
